services:
  - type: web
    name: codesync-backend
    env: node
    repo: https://github.com/Harshit-Arya-07/CodeSync.git
    region: oregon
    plan: free
    branch: main
    buildCommand: "npm ci && npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: ORIGIN
        value: https://codesync.onrender.com
    healthCheckPath: /api/health